Vagrant.configure("2") do |config|
	config.vm.box = "debian/buster64"
	config.ssh.insert_key = false

	config.vm.provider "virtualbox" do |vb|
		vb.memory = 256
	end

	# LAMP Server 
	config.vm.define "lamp" do |server|
		server.vm.hostname = "lamp.debian10"
		server.vm.network "private_network", ip: "192.168.100.12"
	end
end