Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 256
  end

    # Apache Server 
    config.vm.define "apache" do |server|
      server.vm.hostname = "apache.centos7"
      server.vm.network "private_network", ip: "192.168.100.10"
    end
end
